# MT5 ZeroMQ Configuration
# Adjust mt5_exe_path to your actual MetaTrader 5 installation path

zmq_host: "127.0.0.1"
sys_port: 25555
data_port: 25556
live_port: 25557
stream_port: 25558

# MT5 Executable and Script Configuration
# Update this path to match your MT5 installation
mt5_exe_path: "C:\\Program Files\\MetaTrader 5\\terminal64.exe"
mql5_script: "JsonAPI.ex5"

# Logging and Debug
debug: true

# Connection Parameters
sys_timeout: 3.0
heartbeat: 5
auto_restart: true