# ================================================================
# MT5 ZeroMQ Configuration for JsonAPI EA
# ================================================================
#
# IMPORTANTE: Para uso normal, MT5 debe estar ABIERTO MANUALMENTE 
# con el EA JsonAPI activo ANTES de ejecutar scripts Python.
#
# El EA debe mostrar 😊 (cara feliz) en la esquina del gráfico.
# Ver guía completa: docs/MT5_JSONAPI_SETUP.md
# ================================================================

# ZeroMQ Socket Configuration
zmq_host: "127.0.0.1"  # Loopback address (same machine)
sys_port: 25555        # System commands (REQ/REP)
data_port: 25556       # Historical data (PUSH/PULL)
live_port: 25557       # Live account updates (PUSH/PULL)
stream_port: 25558     # Market data stream (PUSH/PULL)

# MT5 Executable Configuration (only used if auto_restart = true)
mt5_exe_path: "C:\\Program Files\\MetaTrader 5\\terminal64.exe"
mql5_script: "JsonAPI.ex5"

# Logging and Debug
debug: true

# Connection Parameters
sys_timeout: 3.0       # Timeout for sys_request (seconds)
heartbeat: 5           # Heartbeat interval (seconds)

# Auto-Restart Configuration
# WARNING: Set to false for production. MT5 should be running manually.
# Only set to true for automated testing where MT5 needs to be launched automatically.
auto_restart: false