# Grafana Datasources Configuration
apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"

  # TimescaleDB (PostgreSQL)
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: underdog_trading
    user: underdog
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    editable: false
